### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by eallik** [tomahawkins/atom#11]
Can this code base still be safely considered for production use?

**Comment by leepike** [comment]
I'm one of the maintainers for the project. I'll make sure it builds with recent versions of GHC. Atom has been stable for quite some time, so in that respect, it's still OK for "production use". Otherwise, it's not being used widely, so keep that in consideration.

**Comment by eallik** [comment]
Thank you for the reply! Do you know of any production projects that use Atom?

**Comment by leepike** [comment]
Besides Tom's work at Eaton (http://cufp.galois.com/2008/schedule.html), and our use of it as a backend for NASA (http://leepike.github.io/Copilot/), I don't.

**Comment by eallik** [comment]
I only read the Eaton report and I have to admit it's been an amazing source of learning. Led me to stuff like HIL and evolutionary robotics, which is currently very useful information. Thanks!

Can you help me understand though: is Atom reasonable/beneficial for non-real-time systems too? I take it it can simplify also certain aspects of embedded programming that are not timing related (aside from taking away the verbosity of C).

**Comment by leepike** [comment]
> is Atom reasonable/beneficial for non-real-time systems too?

Yes, although there are restrictions that make it difficult to use for general purpose computing---for example, the lack of allocation and compound structures.
