### ISSUE TITLE
required header not included in main file

### ISSUE THREAD

**Issue by eallik** [tomahawkins/atom#13]
Consider http://lpaste.net/470595860065943552:

The `main.c` file generated does not, for some reason, include the necessary `myAtom.h`, which contains the definition of the extern `state`.

**Comment by leepike** [comment]
Sorry for the delay.

If I recall correctly, we don't have a way in Atom to automatically manage necessary includes between files. Therefore, you need to do it manually, something like the following, which you probably already know how to do: https://gist.github.com/leepike/e7d09ed02e294912dda8

I'm going to close the ticket, but if you want to submit an enhancement, that would be fantastic!

**Comment by eallik** [comment]
would that be almost trival though, or at least very straightforward?

**Comment by leepike** [comment]
It's should be too hard, I'd think.
