### ISSUE TITLE
Does not work with GHC 7.10

### ISSUE THREAD

**Issue by ndmitchell** [tomahawkins/atom#9]
The last version on Hackage doesn't work with GHC 7.10, giving the error:

    Language/Atom/Elaboration.hs:209:10:
        No instance for (Applicative Atom)
          arising from the superclasses of an instance declaration
        In the instance declaration for ‘Monad Atom’

This is fixed in the repo. I suggest making a new release.

**Comment by Hodapp87** [comment]
I have a feeling @leepike is waiting on me here. In https://github.com/tomahawkins/atom/pull/8#issuecomment-92384737 I said I'd try to update the examples, and I have not done this yet.

**Comment by leepike** [comment]
Uploaded to Hackage. Thanks.
